on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        run: |
          retry_count=3
          for ((i=1; i<=retry_count; i++)); do
            az storage blob upload-batch --account-name staticsitehostingproject --account-key ${{ secrets.AZURE_STORAGE_KEY }} --auth-mode key --overwrite -d '$web' -s . && break || sleep 15
          done

      - name: Purge CDN endpoint
        run: |
          retry_count=3
          for ((i=1; i<=retry_count; i++)); do
            az cdn endpoint purge --content-paths "/*" --profile-name "StaticSiteHostingProject" --name "staticsiteamc" --resource-group "StaticSiteHostingProjectRG" && break || sleep 15
          done

      - name: logout
        run: |
          az logout
        if: always()
