name: Build and deploy Gatsby site to Azure Blob Storage
on:
  push:
    branches:
      - master #trigger the workflow on push request event for the master branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v2.0.0
        with: 
          source_dir: public #gatsby build generates this file after build
          container_name: $web
          connection_string: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
